//! Module providing KeyCodes and KeyState enums
//! Borrowed from GLFW's Key Input Macros

pub const NUM_KEYS: usize = 123;

#[derive(Clone, Copy)]
pub enum KeyCode {
    KeyUnknown,
    KeySpace,
    KeyApostrophe,
    KeyComma,
    KeyMinus,
    KeyPeriod,
    KeySlash,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    KeySemicolon,
    KeyEqual,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    KeyLeftBracket,
    KeyBackslash,
    KeyRightBracket,
    KeyGraveAccent,
    KeyWorld1,
    KeyWorld2,
    KeyEscape,
    KeyEnter,
    KeyTab,
    KeyBackspace,
    KeyInsert,
    KeyDelete,
    KeyRight,
    KeyLeft,
    KeyDown,
    KeyUp,
    KeyPageUp,
    KeyPageDown,
    KeyHome,
    KeyEnd,
    KeyCapsLock,
    KeyScrollLock,
    KeyNumLock,
    KeyPrintScreen,
    KeyPause,
    KeyF1,
    KeyF2,
    KeyF3,
    KeyF4,
    KeyF5,
    KeyF6,
    KeyF7,
    KeyF8,
    KeyF9,
    KeyF10,
    KeyF11,
    KeyF12,
    KeyF13,
    KeyF14,
    KeyF15,
    KeyF16,
    KeyF17,
    KeyF18,
    KeyF19,
    KeyF20,
    KeyF21,
    KeyF22,
    KeyF23,
    KeyF24,
    KeyF25,
    KeyKp0,
    KeyKp1,
    KeyKp2,
    KeyKp3,
    KeyKp4,
    KeyKp5,
    KeyKp6,
    KeyKp7,
    KeyKp8,
    KeyKp9,
    KeyKpDecimal,
    KeyKpDivide,
    KeyKpMultiply,
    KeyKpSubtract,
    KeyKpAdd,
    KeyKpEnter,
    KeyKpEqual,
    KeyLeftShift,
    KeyLeftControl,
    KeyLeftAlt,
    KeyLeftSuper,
    KeyRightShift,
    KeyRightControl,
    KeyRightAlt,
    KeyRightSuper,
    KeyMenu,
    KeyLast,
}

#[derive(Clone, Copy)]
pub enum KeyState {
    Down,
    Pressed,
    Up,
    NotPressed,
}

impl From<KeyState> for bool {
    fn from(value: KeyState) -> Self {
        match value {
            KeyState::Down | KeyState::Pressed => true,
            _ => false
        }
    }
}

impl From<KeyCode> for usize {
    fn from(value: KeyCode) -> Self {
        match value {
            KeyCode::KeyUnknown => 1,
            KeyCode::KeySpace => 2,
            KeyCode::KeyApostrophe => 3,
            KeyCode::KeyComma => 4,
            KeyCode::KeyMinus => 5,
            KeyCode::KeyPeriod => 6,
            KeyCode::KeySlash => 7,
            KeyCode::Key0 => 8,
            KeyCode::Key1 => 9,
            KeyCode::Key2 => 10,
            KeyCode::Key3 => 11,
            KeyCode::Key4 => 12,
            KeyCode::Key5 => 13,
            KeyCode::Key6 => 14,
            KeyCode::Key7 => 15,
            KeyCode::Key8 => 16,
            KeyCode::Key9 => 17,
            KeyCode::KeySemicolon => 18,
            KeyCode::KeyEqual => 19,
            KeyCode::KeyA => 20,
            KeyCode::KeyB => 21,
            KeyCode::KeyC => 22,
            KeyCode::KeyD => 23,
            KeyCode::KeyE => 24,
            KeyCode::KeyF => 25,
            KeyCode::KeyG => 26,
            KeyCode::KeyH => 27,
            KeyCode::KeyI => 28,
            KeyCode::KeyJ => 29,
            KeyCode::KeyK => 30,
            KeyCode::KeyL => 31,
            KeyCode::KeyM => 32,
            KeyCode::KeyN => 33,
            KeyCode::KeyO => 34,
            KeyCode::KeyP => 35,
            KeyCode::KeyQ => 36,
            KeyCode::KeyR => 37,
            KeyCode::KeyS => 38,
            KeyCode::KeyT => 39,
            KeyCode::KeyU => 40,
            KeyCode::KeyV => 41,
            KeyCode::KeyW => 42,
            KeyCode::KeyX => 43,
            KeyCode::KeyY => 44,
            KeyCode::KeyZ => 45,
            KeyCode::KeyLeftBracket => 46,
            KeyCode::KeyBackslash => 47,
            KeyCode::KeyRightBracket => 48,
            KeyCode::KeyGraveAccent => 49,
            KeyCode::KeyWorld1 => 50,
            KeyCode::KeyWorld2 => 51,
            KeyCode::KeyEscape => 52,
            KeyCode::KeyEnter => 53,
            KeyCode::KeyTab => 54,
            KeyCode::KeyBackspace => 55,
            KeyCode::KeyInsert => 56,
            KeyCode::KeyDelete => 57,
            KeyCode::KeyRight => 58,
            KeyCode::KeyLeft => 59,
            KeyCode::KeyDown => 60,
            KeyCode::KeyUp => 61,
            KeyCode::KeyPageUp => 62,
            KeyCode::KeyPageDown => 63,
            KeyCode::KeyHome => 64,
            KeyCode::KeyEnd => 65,
            KeyCode::KeyCapsLock => 66,
            KeyCode::KeyScrollLock => 67,
            KeyCode::KeyNumLock => 68,
            KeyCode::KeyPrintScreen => 69,
            KeyCode::KeyPause => 70,
            KeyCode::KeyF1 => 71,
            KeyCode::KeyF2 => 72,
            KeyCode::KeyF3 => 73,
            KeyCode::KeyF4 => 74,
            KeyCode::KeyF5 => 75,
            KeyCode::KeyF6 => 76,
            KeyCode::KeyF7 => 77,
            KeyCode::KeyF8 => 78,
            KeyCode::KeyF9 => 79,
            KeyCode::KeyF10 => 80,
            KeyCode::KeyF11 => 81,
            KeyCode::KeyF12 => 82,
            KeyCode::KeyF13 => 83,
            KeyCode::KeyF14 => 84,
            KeyCode::KeyF15 => 85,
            KeyCode::KeyF16 => 86,
            KeyCode::KeyF17 => 87,
            KeyCode::KeyF18 => 88,
            KeyCode::KeyF19 => 89,
            KeyCode::KeyF20 => 90,
            KeyCode::KeyF21 => 91,
            KeyCode::KeyF22 => 92,
            KeyCode::KeyF23 => 93,
            KeyCode::KeyF24 => 94,
            KeyCode::KeyF25 => 95,
            KeyCode::KeyKp0 => 96,
            KeyCode::KeyKp1 => 97,
            KeyCode::KeyKp2 => 98,
            KeyCode::KeyKp3 => 99,
            KeyCode::KeyKp4 => 100,
            KeyCode::KeyKp5 => 101,
            KeyCode::KeyKp6 => 102,
            KeyCode::KeyKp7 => 103,
            KeyCode::KeyKp8 => 104,
            KeyCode::KeyKp9 => 105,
            KeyCode::KeyKpDecimal => 106,
            KeyCode::KeyKpDivide => 107,
            KeyCode::KeyKpMultiply => 108,
            KeyCode::KeyKpSubtract => 109,
            KeyCode::KeyKpAdd => 110,
            KeyCode::KeyKpEnter => 111,
            KeyCode::KeyKpEqual => 112,
            KeyCode::KeyLeftShift => 113,
            KeyCode::KeyLeftControl => 114,
            KeyCode::KeyLeftAlt => 115,
            KeyCode::KeyLeftSuper => 116,
            KeyCode::KeyRightShift => 117,
            KeyCode::KeyRightControl => 118,
            KeyCode::KeyRightAlt => 119,
            KeyCode::KeyRightSuper => 120,
            KeyCode::KeyMenu => 121,
            KeyCode::KeyLast => 122,
        }
    }
}
